name: skygan_2_3_110_xpu
channels:
  - https://software.repos.intel.com/python/conda
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - pytorch=2.3.1
  - intel-extension-for-pytorch=2.3.110
  - numpy>=1.20
  #- numpy==1.26.4
  - click>=8.0
  - pillow=8.3.1
  - scipy=1.7.1
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - matplotlib=3.4.2
  - imageio=2.9.0
  - opencv=4.6.0
  - pandas=1.5.2
  - diskcache=5.4.0
  - pybind11=2.9.2
  - pip:
    # for visualiser
    - imgui==1.3.0
    - glfw==2.2.0
    - pyopengl==3.1.5
    # for gen_video.py storing output to .mp4
    - imageio-ffmpeg==0.4.3
    # for loading .png training datasets
    - pyspng==0.1.1
    # for training/FID computation
    - psutil==5.9.4
